// <auto-generated />
using System;
using Formula1WebApplication.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formula1WebApplication.Infrastructure.Migrations
{
    [DbContext(typeof(FormulaOneDbContext))]
    [Migration("20240331092410_DataSeeded")]
    partial class DataSeeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for event");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time of the event");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Detailed description of the event");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL to an image representing the event");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The location where the event is held");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the event");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasComment("Event Organizer Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("User Id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An exclusive opportunity to meet your favorite Formula 1 drivers.",
                            ImageUrl = "https://www.circuitcat.com/wp-content/uploads/2019/05/1805100318_sainz.jpg",
                            Location = "Melbourne, Australia",
                            Name = "F1 Meet and Greet",
                            OrganizerId = 1,
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get the chance to take autographs from the top F1 pilots.",
                            ImageUrl = "https://cdn-5.motorsport.com/images/amp/0R5W8yZ6/s6/f1-british-gp-2018-max-verstappen-red-bull-racing-signs-autographs-for-fans-8649080.jpg",
                            Location = "Jeddah, Saudi Arabia",
                            Name = "Autograph Session",
                            OrganizerId = 1,
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A behind-the-scenes look at the teams' preparations for the race weekend.",
                            ImageUrl = "https://d3cm515ijfiu6w.cloudfront.net/wp-content/uploads/2022/06/16115532/Charles-Leclercs-car-in-the-Ferrari-garage-planetF1.jpg",
                            Location = "Sakhir, Bahrain",
                            Name = "Exclusive Team Garage Preview",
                            OrganizerId = 1,
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"
                        });
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for news article");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Detailed description or content of the article");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL to an image related to the news article");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasComment("News Article Organizer Id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The title of the article");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Norris reckons he could have beaten Leclerc in Melbourne with a better strategy – but is he right? Max Verstappen’s retirement from Australian Grand Prix in the opening laps, along with Sergio Perez’s P6 start from the grid, set up an exciting battle for the race win and resulted in a very different looking podium. Ferrari finished the race on the top two steps closely followed by Lando Norris, with all of the top three showing the speed capable of taking the fastest lap (ultimately secured by Charles Leclerc). However, was a better finish possible for Norris? Former Aston Martin Head of Strategy Bernie Collins investigates…",
                            ImageUrl = "https://cdn-1.motorsport.com/images/amp/2wBdPEq0/s1000/lando-norris-mclaren-prepares-.jpg",
                            OrganizerId = 1,
                            Title = "The Strategist"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Daniel Ricciardo didn’t manage to score points on home soil in Melbourne, on a day where his team mate finished seventh and got the team’s account up and running in the constructors’. Having now been out-qualified by Yuki Tsunoda in the first three races, the Australian was in a reflective mood after coming home in 12th place. Ricciardo’s woes in Australia stretched back to qualifying when he lost his lap time in Q1 for a clear track limits infringement, which dropped him to P18 on the grid. Although there were three retirements in the race and two Virtual Safety Car periods, Ricciardo ran out of time to climb into the points.",
                            ImageUrl = "https://thejudge13.com/wp-content/uploads/2024/02/daniel-ricciardo.webp",
                            OrganizerId = 1,
                            Title = "Not where I expected to be"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Australian Grand Prix in Melbourne served up a superb victory for Carlos Sainz, with plenty of other impressive performances throughout the field. As usual, former IndyCar star and F1 TV pundit James Hinchcliffe was watching closely and has picked out the five drivers who impressed him the most across the race weekend at the Albert Park circuit… Carlos Sainz – P1 - This one is an inevitability, so let’s get it out of the way first. In what many pundits have labeled as Sainz’s greatest drive in F1, the Spaniard capitalised on a rare reliability misstep from Red Bull that eliminated Max Verstappen from contention only a handful of laps into the race.",
                            ImageUrl = "https://i.cbc.ca/1.6509174.1656870708!/fileImage/httpImage/1406549790.jpg",
                            OrganizerId = 1,
                            Title = "Hinch's heroes"
                        });
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for organizer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Contact phone number for organizer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Organizer User Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhoneNumber = "+359123123123",
                            UserId = "dea12856-c198-4129-b3f3-b893d8395082"
                        });
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for pilot");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Short biography of the pilot");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Pilot's first name");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Path to the pilot's image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Pilot's last name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Pilot's nationality");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the team the pilot is associated with");

                    b.HasKey("Id");

                    b.ToTable("Pilots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "He’s Max by name, and max by nature. Arriving as Formula 1’s youngest ever competitor at just 17 years old, Verstappen pushed his car, his rivals and the sport’s record books to the limit. The baby-faced Dutchman with the heart of a lion took the Toro Rosso – and then the Red Bull – by the horns with his instinctive racing style.",
                            FirstName = "Max",
                            ImagePath = "\\wwwroot\\images\\pilots\\maxverstappen.png",
                            LastName = "Verstappen",
                            Nationality = "Dutch",
                            TeamName = "Red Bull Racing"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Leclerc arrived in F1 on a tidal wave of expectation. He showcased a dazzling array of skills from scorching pole positions, commanding victories – even when his car caught fire twice at Silverstone – to an ability to muscle his way through the pack. Winning back-to-back championships also taught Leclerc how to handle pressure, another useful tool in Formula 1 racing.",
                            FirstName = "Charles",
                            ImagePath = "\\wwwroot\\images\\pilots\\charlesleclerc.png",
                            LastName = "Leclerc",
                            Nationality = "Monegasque",
                            TeamName = "Ferrari"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "He’s the fighter with a gentle touch from the land of the Lucha Libre.Perez’s reputation in F1 has been built on opposite approaches to Grand Prix racing. On the one hand, he is a punchy combatant who wrestles his way through the pack and into the points. Never afraid to add a bit of spice to his on-track encounters, even his team mates don’t always escape the Mexican’s heat.",
                            FirstName = "Sergio",
                            ImagePath = "\\wwwroot\\images\\pilots\\sergioperez.png",
                            LastName = "Perez",
                            Nationality = "Mexican",
                            TeamName = "Red Bull Racing"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "He’s the matador from Madrid racing royalty. After entering F1’s Bull Ring paired alongside Max Verstappen at Toro Rosso in 2015, Sainz quickly showed his fighting spirit. A tenacious racer, he puts the car on the edge as he hustles his way through the pack. No wonder Sainz has earned the nickname Chilli.",
                            FirstName = "Carlos",
                            ImagePath = "\\wwwroot\\images\\pilots\\carlossainz.png",
                            LastName = "Sainz",
                            Nationality = "Spanish",
                            TeamName = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Born in Melbourne, just a stone’s throw away from the Australian Grand Prix venue, a young Oscar Piastri’s dreams of one day racing in Formula 1 were ignited by the sport’s star drivers roaring around his local streets, otherwise known as Albert Park.",
                            FirstName = "Oscar",
                            ImagePath = "\\wwwroot\\images\\pilots\\oscarpiastri.png",
                            LastName = "Piastri",
                            Nationality = "Australian",
                            TeamName = "McLaren"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "He has flair and fighting spirit in bountiful supply. McLaren had the British teenager on their books for two years before fast-tracking him into F1’s galaxy of stars in 2019. A firecracker in his junior career, with a penchant for pole positions and wheel-to-wheel tussles, Norris didn’t let them down.",
                            FirstName = "Lando",
                            ImagePath = "\\wwwroot\\images\\pilots\\landonorris.png",
                            LastName = "Norris",
                            Nationality = "British",
                            TeamName = "McLaren"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "He’s the driver with the motto: “If in doubt, go flat out”. George Russell has lived by it throughout his F1 career to date, out-qualifying seasoned team mate Robert Kubica at all 21 Grands Prix in his rookie season, putting Williams back on the podium in 2021, and landing his first race win with Mercedes in 2022.",
                            FirstName = "George",
                            ImagePath = "\\wwwroot\\images\\pilots\\georgerussel.png",
                            LastName = "Russell",
                            Nationality = "British",
                            TeamName = "Mercedes"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Fiercely competitive, Alonso is not shy about his talent, rating himself as 9/10 “in everything”, and few in the know would disagree, with his performances in F1 characterised by blistering speed, brilliant tactical thinking, exemplary race craft, a razor-sharp eye for detail and a relentless determination to win.",
                            FirstName = "Fernando",
                            ImagePath = "\\wwwroot\\images\\pilots\\fernandoalonso.png",
                            LastName = "Alonso",
                            Nationality = "Spanish",
                            TeamName = "Alpine"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "There is no such thing as too much too soon for Stroll, a teenage sensation with a wet weather predilection. One of the cool kids on the grid, Stroll was unveiled shortly after his 18th birthday by Williams – before he finished high school and got his road licence. Stroll meant business in his debut 2017 season, setting records on the way. ",
                            FirstName = "Lance",
                            ImagePath = "\\wwwroot\\images\\pilots\\lancestroll.png",
                            LastName = "Stroll",
                            Nationality = "Canadian",
                            TeamName = "Aston Martin"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "‘Still I Rise’ – these are the words emblazoned across the back of Lewis Hamilton’s helmet and tattooed across his shoulders, and ever since annihilating expectations with one of the greatest rookie performances in F1 history in 2007, that’s literally all he’s done: risen to the top of the all-time pole positions list.",
                            FirstName = "Lewis",
                            ImagePath = "\\wwwroot\\images\\pilots\\lewishamilton.png",
                            LastName = "Hamilton",
                            Nationality = "British",
                            TeamName = "Mercedes"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "In the entire history of Formula 1, no Japanese driver has ever won a World Championship Grand Prix. Red Bull certainly think so, with the youngster very much on the path to their senior team if he continues to impress as he has done over the past few years. Tsunoda's ascent to the top tier of motorsport was astonishingly rapid.",
                            FirstName = "Yuki",
                            ImagePath = "\\wwwroot\\images\\pilots\\yukitsunoda.png",
                            LastName = "Tsunoda",
                            Nationality = "Japanese",
                            TeamName = "AlphaTauri"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "He’s the Superhero with the talent to become a racing superstar – if only he could get to flex his muscles with a top team. F1’s 'Hulk' has shown incredible strength and stamina as a midfield marauder for Williams, Force India, Sauber, Renault, Racing Point, Aston Martin and Haas during a career spanning back to 2010.",
                            FirstName = "Nico",
                            ImagePath = "\\wwwroot\\images\\pilots\\nicohulkenberg.png",
                            LastName = "Hulkenberg",
                            Nationality = "German",
                            TeamName = "Aston Martin"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Call him a lone ranger or a maverick, but Magnussen is in Formula 1 for one reason only – to race. He may be a second-generation F1 driver – following his father, Jan, onto the grid – but Magnussen’s idols are from the ‘golden era’ of Grand Prix racing when the likes of Juan Manuel Fangio and Stirling Moss risked it all for the love of the sport.",
                            FirstName = "Kevin",
                            ImagePath = "\\wwwroot\\images\\pilots\\kevinmagnussen.png",
                            LastName = "Magnussen",
                            Nationality = "Danish",
                            TeamName = "Haas"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Born in London but racing under the flag of Thailand, Alexander Albon’s first word was in fact Italian. That word was Ferrari – though it was with another Italian team that he got his big F1 break. Idolising Michael Schumacher and dreaming of one day racing in Formula 1, the junior Albon was pipped to the 2016 GP3.",
                            FirstName = "Alex",
                            ImagePath = "\\wwwroot\\images\\pilots\\alexalbon.png",
                            LastName = "Albon",
                            Nationality = "Thai",
                            TeamName = "Williams"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "China had never boasted a Grand Prix starter among its citizens – until Zhou Guanyu changed that state of affairs, after receiving the call-up to make his F1 debut for Alfa Romeo, now Kick Sauber, in 2022. The Shanghai-born racer attended his home city’s inaugural Grand Prix in 2004 at the age of five, cheering on his hero Fernando Alonso.",
                            FirstName = "Guanyu",
                            ImagePath = "\\wwwroot\\images\\pilots\\guanyuzhou.png",
                            LastName = "Zhou",
                            Nationality = "Chinese",
                            TeamName = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 16,
                            Biography = "The self-styled “Honey Badger” is fuzzy on the outside and feisty on the inside. Drivers beware because behind Ricciardo’s laidback persona and big grin is a razor-sharp racer with a bite. The Australian combines all-out speed with impressive race craft. Never afraid to push to the limits if it means pulling off a pass, Ricciardo is a proven race-winner.",
                            FirstName = "Daniel",
                            ImagePath = "\\wwwroot\\images\\pilots\\danielricciardo.png",
                            LastName = "Ricciardo",
                            Nationality = "Australian",
                            TeamName = "McLaren"
                        },
                        new
                        {
                            Id = 17,
                            Biography = "If there’s one word that dominates Esteban Ocon’s career, it’s ‘sacrifice’. Back when he was just a promising karter, Ocon’s parents sold their house, put their jobs on hold, and began a life on the road, living in a caravan and travelling from circuit to circuit to support their son’s burgeoning career.",
                            FirstName = "Esteban",
                            ImagePath = "\\wwwroot\\images\\pilots\\estebanocon.png",
                            LastName = "Ocon",
                            Nationality = "French",
                            TeamName = "Alpine"
                        },
                        new
                        {
                            Id = 18,
                            Biography = "The flying Frenchman was called up to make his 2017 debut in Malaysia in place of Daniil Kvyat and, after proving his mettle, he was named a Toro Rosso driver the following year.  A further 21 races into his fledgling career, Gasly was moved up again – this time to replace Red Bull big gun Daniel Ricciardo.",
                            FirstName = "Pierre",
                            ImagePath = "\\wwwroot\\images\\pilots\\pierregasly.png",
                            LastName = "Gasly",
                            Nationality = "French",
                            TeamName = "AlphaTauri"
                        },
                        new
                        {
                            Id = 19,
                            Biography = "Learning his craft on Finnish roads of ice and snow, he was born to be a Grand Prix racer. Bottas explains that if you can drive on the frozen roads of his homeland then you can drive anywhere. Then there’s the Finnish mentality –reserved, diligent and calm the fast lane of F1 doesn’t faze him.",
                            FirstName = "Valtteri",
                            ImagePath = "\\wwwroot\\images\\pilots\\valtteribottas.png",
                            LastName = "Bottas",
                            Nationality = "Finnish",
                            TeamName = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 20,
                            Biography = "Logan Sargeant became F1’s first American driver in almost eight years, giving the country a home favourite to cheer once more. Winner in karting, championship glory eluded Sargeant after he made the transition to single-seater racing, but pole positions and race victories in almost every category he contested underlined his raw speed and potential.",
                            FirstName = "Logan",
                            ImagePath = "\\wwwroot\\images\\pilots\\logansargeant.png",
                            LastName = "Sargeant",
                            Nationality = "American",
                            TeamName = "Williams"
                        });
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for race");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CircuitInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Information about the race circuit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time of the race");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL to an image representing the race");

                    b.Property<int>("Laps")
                        .HasColumnType("int")
                        .HasComment("The number of laps in the race");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The location where the race is held");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the race");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasComment("Race Organizer Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("User Id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitInfo = "Built for the Bahrain International Circuit in December 2002. It has a blank, sandy canvas to work with, and with that fashioned the technical, 5.4km track designed by Hermann Tilke.",
                            Date = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://cdn.racingnews365.com/2024/Verstappen/_1092x683_crop_center-center_85_none/SI202403020340_hires_jpeg_24bit_rgb.jpg?v=1709395733",
                            Laps = 57,
                            Location = "Bahrain International Circuit",
                            Name = "Bahrain Grand Prix",
                            OrganizerId = 1,
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"
                        },
                        new
                        {
                            Id = 2,
                            CircuitInfo = "The Jeddah Corniche Circuit is a temporary street circuit, located on the Corniche – a 30km coastal resort area of the ancient Saudi Arabian city of Jeddah.",
                            Date = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://cdn.racingnews365.com/2024/_1092x683_crop_center-center_85_none/Qiddiya-street-track-2.jpg?v=1709640021",
                            Laps = 50,
                            Location = "Jeddah Corniche Circuit",
                            Name = "Saudi Arabia Grand Prix",
                            OrganizerId = 1,
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"
                        },
                        new
                        {
                            Id = 3,
                            CircuitInfo = "The deal to host Formula 1 in Melbourne was done in 1993, using a mixture of the existing roads around the city’s Albert Park – mainly Aughtie Drive and Lakeside Drive.",
                            Date = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245019/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Australia.jpg.transform/9col/image.jpg",
                            Laps = 58,
                            Location = "Melbourne Grand Prix Circuit",
                            Name = "Australia Grand Prix",
                            OrganizerId = 1,
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9ecf8983-890a-42af-aa3f-1adb99a4b68b",
                            Email = "organizer@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "organizer@mail.com",
                            NormalizedUserName = "organizer@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAELhYFf97FnRnDubWxvTwtd2A19oO19HKuFY/DH8Fvoy/1Nt48OBwMTIDHPffA9bHHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1636cf4c-82ff-4c1e-80f8-ebdcd65239c8",
                            TwoFactorEnabled = false,
                            UserName = "organizer@mail.com"
                        },
                        new
                        {
                            Id = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2daa778-2223-43c3-b7bc-eacf8c008b59",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "guest@mail.com",
                            NormalizedUserName = "guest@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEAh3NH09bw4bqJYSKJ8QL2bpvA4yoADG6fElzg59g/vprRjEMS52YfeLEhCvbsWUuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4391048-353f-4129-aa19-fcf8551b2ec9",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Event", b =>
                {
                    b.HasOne("Formula1WebApplication.Infrastructure.Data.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.NewsArticle", b =>
                {
                    b.HasOne("Formula1WebApplication.Infrastructure.Data.Models.Organizer", "Organizer")
                        .WithMany("NewsArticles")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Organizer", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Race", b =>
                {
                    b.HasOne("Formula1WebApplication.Infrastructure.Data.Models.Organizer", "Organizer")
                        .WithMany("Races")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Formula1WebApplication.Infrastructure.Data.Models.Organizer", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("NewsArticles");

                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
